% Batch compute nuisance-regressed mALFF for all MNI-space BOLD files
% generated by spm_bold_to_mni.m using SPM12.
%
% The script expects normalized BOLD outputs in D:\output and the matching
% SPM work tree in D:\output\spm_work_batch_to_mni. mALFF outputs are saved
% under D:\predata\malff_output.

clear;
clc;

SPM_PATH = 'M:\Documents\MATLAB\spm12';

base_dir = fileparts(mfilename('fullpath'));
RAW_INPUT_DIR = 'D:\openneuro data';
INPUT_BOLD_DIR = 'D:\output';

template_file = fullfile(base_dir, 'mni152.nii');
WORK_ROOT = fullfile(INPUT_BOLD_DIR, 'spm_work_batch_to_mni');
MALFF_OUT_DIR = fullfile(base_dir, 'malff_output');
STATUS_CSV = fullfile(MALFF_OUT_DIR, 'batch_malff_status.csv');

BOLD_PATTERN = '*_space-MNI152_spm.nii';

TR_SECONDS = 3.0;
LOW_FREQ = 0.01;
HIGH_FREQ = 0.08;
CHUNK_SIZE = 10000;
TPM_THRESHOLD = 0.80;
OVERWRITE_OUTPUT = false;
CONTINUE_ON_ERROR = true;

addpath(SPM_PATH);

if exist('spm', 'file') ~= 2
    error('SPM was not found. Check SPM_PATH: %s', SPM_PATH);
end

ensure_file(template_file, 'MNI template');
ensure_existing_dir(RAW_INPUT_DIR, 'raw OpenNeuro dataset');
ensure_existing_dir(INPUT_BOLD_DIR, 'normalized BOLD directory');
ensure_existing_dir(WORK_ROOT, 'SPM work directory');
ensure_dir(MALFF_OUT_DIR);

spm('Defaults', 'fMRI');
spm_jobman('initcfg');

bold_files = find_normalized_bold_files(INPUT_BOLD_DIR, BOLD_PATTERN);
if isempty(bold_files)
    error('No normalized BOLD files matching %s were found in: %s', ...
        BOLD_PATTERN, INPUT_BOLD_DIR);
end

fprintf('Input normalized BOLD directory: %s\n', INPUT_BOLD_DIR);
fprintf('Raw OpenNeuro dataset: %s\n', RAW_INPUT_DIR);
fprintf('MNI template: %s\n', template_file);
fprintf('SPM work root: %s\n', WORK_ROOT);
fprintf('mALFF output directory: %s\n', MALFF_OUT_DIR);
fprintf('Normalized BOLD files found: %d\n\n', numel(bold_files));

status_rows = cell(0, 6);

for i = 1:numel(bold_files)
    bold_file = bold_files{i};
    bold_stem = nifti_stem(bold_file);
    base_stem = strip_suffix(bold_stem, '_space-MNI152_spm');

    if isempty(base_stem)
        message = 'Normalized BOLD file name does not end with _space-MNI152_spm';
        fprintf('SKIP: %s\n', message);
        status_rows = append_status(status_rows, '', bold_file, '', ...
            'SKIPPED', message);
        write_status_csv(STATUS_CSV, status_rows);
        continue;
    end

    subject_id = extract_subject_id_from_stem(base_stem);
    subject_run_dir = fullfile(WORK_ROOT, subject_id, safe_filename(base_stem));
    nifti_dir = fullfile(subject_run_dir, 'nifti');
    out_malff_file = make_malff_output_file(MALFF_OUT_DIR, base_stem);
    raw_json_file = find_raw_bold_json(RAW_INPUT_DIR, subject_id, base_stem);
    tr_seconds = read_repetition_time(raw_json_file, TR_SECONDS);

    fprintf('\n============================================================\n');
    fprintf('File %d/%d: %s\n', i, numel(bold_files), base_stem);
    fprintf('============================================================\n');
    fprintf('Subject: %s\n', subject_id);
    fprintf('Normalized BOLD: %s\n', bold_file);
    fprintf('Raw BOLD JSON: %s\n', printable_path(raw_json_file));
    fprintf('TR for mALFF: %.6g s\n', tr_seconds);
    fprintf('Output mALFF: %s\n', out_malff_file);

    if should_skip_existing_output(out_malff_file, OVERWRITE_OUTPUT)
        message = 'Valid output already exists; set OVERWRITE_OUTPUT=true to rerun';
        fprintf('SKIP: %s\n', message);
        status_rows = append_status(status_rows, subject_id, bold_file, ...
            out_malff_file, 'SKIPPED', message);
        write_status_csv(STATUS_CSV, status_rows);
        continue;
    end

    try
        run_malff_for_bold( ...
            bold_file, out_malff_file, subject_run_dir, nifti_dir, ...
            template_file, tr_seconds, LOW_FREQ, HIGH_FREQ, CHUNK_SIZE, ...
            TPM_THRESHOLD);

        message = 'Done';
        status_rows = append_status(status_rows, subject_id, bold_file, ...
            out_malff_file, 'DONE', message);
        write_status_csv(STATUS_CSV, status_rows);
    catch ME
        message = clean_message(ME.message);
        fprintf(2, 'FAILED: %s\n', message);
        status_rows = append_status(status_rows, subject_id, bold_file, ...
            out_malff_file, 'FAILED', message);
        write_status_csv(STATUS_CSV, status_rows);

        if ~CONTINUE_ON_ERROR
            rethrow(ME);
        end
    end
end

fprintf('\nBatch finished.\n');
fprintf('Status CSV: %s\n', STATUS_CSV);
fprintf('mALFF outputs: %s\n', MALFF_OUT_DIR);


function run_malff_for_bold(bold_file, out_malff_file, subject_run_dir, ...
    nifti_dir, template_file, tr_seconds, low_freq, high_freq, chunk_size, ...
    tpm_threshold)

    ensure_file(bold_file, 'MNI-space BOLD');
    ensure_file(template_file, 'MNI template');
    ensure_existing_dir(subject_run_dir, 'subject work directory');
    ensure_existing_dir(nifti_dir, 'subject NIfTI directory');

    deformation_file = select_latest_matching_file( ...
        nifti_dir, 'y_*.nii', 'forward deformation field');
    native_wm_file = select_latest_matching_file( ...
        nifti_dir, 'c2*.nii', 'native-space WM probability map');
    native_csf_file = select_latest_matching_file( ...
        nifti_dir, 'c3*.nii', 'native-space CSF probability map');
    mni_wm_file = select_latest_matching_file( ...
        nifti_dir, 'wc2*.nii', 'subject-specific MNI WM probability map');
    mni_csf_file = select_latest_matching_file( ...
        nifti_dir, 'wc3*.nii', 'subject-specific MNI CSF probability map');

    fprintf('SPM work dir: %s\n', subject_run_dir);
    fprintf('Native WM: %s\n', native_wm_file);
    fprintf('Native CSF: %s\n', native_csf_file);
    fprintf('Deformation field: %s\n', deformation_file);

    Vbold = spm_vol(bold_file);
    n_timepoints = numel(Vbold);
    if n_timepoints < 2
        error('Expected a 4D BOLD image with multiple timepoints: %s', ...
            bold_file);
    end

    fprintf('Loading normalized BOLD data.\n');
    bold_data = zeros([Vbold(1).dim n_timepoints], 'single');
    for t = 1:n_timepoints
        bold_data(:, :, :, t) = single(spm_read_vols(Vbold(t)));
    end

    header_tr = 0;
    if isfield(Vbold(1), 'private') && isfield(Vbold(1).private, 'timing')
        try
            header_tr = Vbold(1).private.timing.tspace;
        catch
            header_tr = 0;
        end
    end

    if header_tr > 0
        fprintf('BOLD header TR: %.6g s\n', header_tr);
    else
        fprintf(['BOLD header TR is missing or unavailable; using ' ...
            'TR_SECONDS=%.6g s.\n'], tr_seconds);
    end

    finite_mean = finite_nanmean_4d(bold_data);
    temporal_std = finite_nanstd_4d(bold_data);

    fprintf('Resampling MNI template to BOLD grid if needed.\n');
    template_data = resample_scalar_to_ref(template_file, Vbold(1), 1);
    template_mask = isfinite(template_data) & template_data > 0;
    mask_3d = template_mask & isfinite(finite_mean) & temporal_std > 0;

    fprintf('Building nuisance design matrix.\n');
    nuisance_design = build_nuisance_design( ...
        bold_data, mask_3d, Vbold(1), n_timepoints, subject_run_dir, ...
        deformation_file, native_wm_file, native_csf_file, ...
        mni_wm_file, mni_csf_file, tpm_threshold);

    [alff_data, valid_mask] = compute_alff( ...
        bold_data, mask_3d, nuisance_design, tr_seconds, low_freq, ...
        high_freq, chunk_size);

    valid_alff = alff_data(valid_mask);
    valid_alff = valid_alff(isfinite(valid_alff));
    global_mean_alff = mean(double(valid_alff));

    if isempty(valid_alff) || ~isfinite(global_mean_alff) || global_mean_alff <= 0
        error('Cannot compute mALFF because the global mean ALFF is invalid.');
    end

    malff_data = zeros(size(alff_data), 'single');
    malff_data(valid_mask) = single(double(alff_data(valid_mask)) ./ ...
        global_mean_alff);

    fprintf('Global mean ALFF inside mask: %.10g\n', global_mean_alff);
    fprintf('Saving mALFF: %s\n', out_malff_file);
    save_3d_like(malff_data, Vbold(1), out_malff_file);

    fprintf('Done.\n');
end


function files = find_normalized_bold_files(input_dir, bold_pattern)
    entries = dir(fullfile(input_dir, bold_pattern));
    entries = entries(~[entries.isdir]);

    files = cell(numel(entries), 1);
    for i = 1:numel(entries)
        files{i} = fullfile(entries(i).folder, entries(i).name);
    end

    files = sort_file_paths(files);
end


function output_file = make_malff_output_file(out_dir, base_stem)
    ensure_dir(out_dir);
    output_file = fullfile(out_dir, [safe_filename(base_stem) ...
        '_mALFF_nuisanceRegressed.nii']);
end


function tf = should_skip_existing_output(output_file, overwrite_output)
    tf = false;

    if overwrite_output || exist(output_file, 'file') ~= 2
        return;
    end

    try
        validate_nifti_file(output_file);
        tf = true;
    catch ME
        warning('Existing output is invalid and will be rerun: %s\nReason: %s', ...
            output_file, clean_message(ME.message));
        delete(output_file);
    end
end


function validate_nifti_file(nifti_file)
    try
        headers = spm_vol(nifti_file);
        if isempty(headers)
            error('SPM could not read any volumes.');
        end
        spm_read_vols(headers(1));
    catch ME
        error('Invalid NIfTI file: %s. %s', nifti_file, clean_message(ME.message));
    end
end


function subject_id = extract_subject_id_from_stem(stem)
    subject_id = regexp(stem, '^sub-[^_]+', 'match', 'once');
    if isempty(subject_id)
        subject_id = strtok(stem, '_');
    end
    if isempty(subject_id)
        error('Could not extract subject id from stem: %s', stem);
    end
end


function json_file = find_raw_bold_json(raw_input_dir, subject_id, base_stem)
    json_name = [base_stem '.json'];
    exact_file = fullfile(raw_input_dir, subject_id, 'func', json_name);

    if exist(exact_file, 'file') == 2
        json_file = exact_file;
        return;
    end

    matches = find_files_recursive(raw_input_dir, json_name);
    matches = sort_file_paths(matches);

    if isempty(matches)
        warning('No raw BOLD JSON found for %s under: %s', ...
            base_stem, raw_input_dir);
        json_file = '';
        return;
    end

    if numel(matches) > 1
        warning('Multiple raw BOLD JSON files found for %s; using: %s', ...
            base_stem, matches{1});
    end

    json_file = matches{1};
end


function tr_seconds = read_repetition_time(json_file, default_tr_seconds)
    tr_seconds = default_tr_seconds;

    if isempty(json_file)
        warning('Using default TR_SECONDS=%.6g s because raw BOLD JSON was not found.', ...
            default_tr_seconds);
        return;
    end

    try
        metadata = jsondecode(fileread(json_file));
        if ~isfield(metadata, 'RepetitionTime')
            warning('RepetitionTime is missing in %s; using TR_SECONDS=%.6g s.', ...
                json_file, default_tr_seconds);
            return;
        end

        value = metadata.RepetitionTime;
        if isnumeric(value) && ~isempty(value) && isfinite(value(1)) && value(1) > 0
            tr_seconds = double(value(1));
        else
            warning('Invalid RepetitionTime in %s; using TR_SECONDS=%.6g s.', ...
                json_file, default_tr_seconds);
        end
    catch ME
        warning('Could not read RepetitionTime from %s; using TR_SECONDS=%.6g s. Reason: %s', ...
            json_file, default_tr_seconds, clean_message(ME.message));
    end
end


function display_text = printable_path(file_path)
    if isempty(file_path)
        display_text = '(not found)';
    else
        display_text = file_path;
    end
end


function stripped = strip_suffix(text, suffix)
    if ends_with(text, suffix)
        stripped = text(1:end - numel(suffix));
    else
        stripped = '';
    end
end


function file_path = select_latest_matching_file(root_dir, pattern, label)
    files = dir(fullfile(root_dir, pattern));
    files = files(~[files.isdir]);
    if isempty(files)
        error('No %s found under: %s', label, root_dir);
    end

    [~, order] = sort([files.datenum], 'descend');
    file_path = fullfile(files(order(1)).folder, files(order(1)).name);
end


function rows = append_status(rows, subject_id, bold_file, output_file, status, message)
    rows(end + 1, :) = { ...
        char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')), ...
        subject_id, bold_file, output_file, status, clean_message(message)};
end


function write_status_csv(csv_file, rows)
    [csv_dir, ~, ~] = fileparts(csv_file);
    ensure_dir(csv_dir);

    fid = fopen(csv_file, 'w');
    if fid < 0
        error('Could not open status CSV for writing: %s', csv_file);
    end

    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '"Timestamp","Subject","BoldFile","OutputFile","Status","Message"\n');
    for i = 1:size(rows, 1)
        fprintf(fid, '%s,%s,%s,%s,%s,%s\n', ...
            csv_escape(rows{i, 1}), csv_escape(rows{i, 2}), ...
            csv_escape(rows{i, 3}), csv_escape(rows{i, 4}), ...
            csv_escape(rows{i, 5}), csv_escape(rows{i, 6}));
    end
end


function text = csv_escape(value)
    if isempty(value)
        value = '';
    elseif isnumeric(value)
        value = num2str(value);
    elseif islogical(value)
        value = mat2str(value);
    end

    text = char(value);
    text = clean_message(text);
    text = strrep(text, '"', '""');
    text = ['"' text '"'];
end


function message = clean_message(message)
    message = char(message);
    message = regexprep(message, '\r|\n', ' ');
end


function ensure_dir(dir_path)
    if exist(dir_path, 'dir') ~= 7
        mkdir(dir_path);
    end
end


function ensure_existing_dir(dir_path, label)
    if exist(dir_path, 'dir') ~= 7
        error('%s directory not found: %s', label, dir_path);
    end
end


function files = sort_file_paths(files)
    keys = cell(numel(files), 1);
    for i = 1:numel(files)
        keys{i} = lower(files{i});
    end
    [~, order] = sort(keys);
    files = files(order);
end


function files = find_files_recursive(root_dir, pattern)
    files = {};
    if exist(root_dir, 'dir') ~= 7
        return;
    end

    matches = dir(fullfile(root_dir, pattern));
    for i = 1:numel(matches)
        if ~matches(i).isdir
            files{end + 1, 1} = fullfile(root_dir, matches(i).name); %#ok<AGROW>
        end
    end

    entries = dir(root_dir);
    for i = 1:numel(entries)
        if entries(i).isdir && ...
                ~strcmp(entries(i).name, '.') && ...
                ~strcmp(entries(i).name, '..')
            child_dir = fullfile(root_dir, entries(i).name);
            child_files = find_files_recursive(child_dir, pattern);
            files = [files; child_files]; %#ok<AGROW>
        end
    end
end


function safe_name = safe_filename(name)
    safe_name = regexprep(name, '[^A-Za-z0-9_-]', '_');
end


function stem = nifti_stem(file_path)
    [~, name, ext] = fileparts(file_path);
    if strcmpi(ext, '.gz')
        [~, name2, ext2] = fileparts(name);
        if strcmpi(ext2, '.nii')
            stem = name2;
        else
            stem = name;
        end
    else
        stem = name;
    end
end


function tf = ends_with(text, suffix)
    tf = numel(text) >= numel(suffix) && ...
        strcmp(text(end - numel(suffix) + 1:end), suffix);
end


function ensure_file(file_path, label)
    if exist(file_path, 'file') ~= 2
        error('%s file not found: %s', label, file_path);
    end
end


function data = resample_scalar_to_ref(source_file, ref_vol, interp)
    source_vols = spm_vol(source_file);
    source_vol = source_vols(1);

    same_dim = isequal(double(source_vol.dim(:)), double(ref_vol.dim(:)));
    same_mat = max(abs(source_vol.mat(:) - ref_vol.mat(:))) <= 1e-3;

    if same_dim && same_mat
        data = single(spm_read_vols(source_vol));
        return;
    end

    data = zeros(ref_vol.dim, 'single');
    [x_grid, y_grid] = ndgrid(1:ref_vol.dim(1), 1:ref_vol.dim(2));
    n_vox_slice = numel(x_grid);

    for z = 1:ref_vol.dim(3)
        ref_vox = [x_grid(:)'; y_grid(:)'; repmat(z, 1, n_vox_slice); ...
            ones(1, n_vox_slice)];
        xyz_mm = ref_vol.mat * ref_vox;
        source_vox = source_vol.mat \ xyz_mm;
        sampled = spm_sample_vol(source_vol, source_vox(1, :), ...
            source_vox(2, :), source_vox(3, :), interp);
        data(:, :, z) = reshape(single(sampled), ref_vol.dim(1), ref_vol.dim(2));
    end
end


function mean_data = finite_nanmean_4d(data_4d)
    finite_data = isfinite(data_4d);
    tmp = double(data_4d);
    tmp(~finite_data) = 0;
    count = sum(finite_data, 4);
    mean_data = sum(tmp, 4) ./ double(count);
    mean_data(count == 0) = NaN;
end


function std_data = finite_nanstd_4d(data_4d)
    finite_data = isfinite(data_4d);
    mean_data = finite_nanmean_4d(data_4d);
    centered = double(data_4d) - mean_data;
    centered(~finite_data) = 0;
    count = sum(finite_data, 4);
    variance = sum(centered .^ 2, 4) ./ double(count);
    variance(count == 0) = NaN;
    std_data = sqrt(variance);
end


function design = build_nuisance_design(data_4d, mask_3d, ref_vol, n_timepoints, ...
    motion_dir, deformation_file, native_wm_file, native_csf_file, ...
    mni_wm_file, mni_csf_file, tpm_threshold)

    [motion_labels, motion_matrix] = load_motion_regressors(motion_dir, n_timepoints);

    ensure_subject_tissues_in_mni( ...
        deformation_file, native_wm_file, native_csf_file, mni_wm_file, mni_csf_file);

    fprintf('Using subject-specific MNI WM map: %s\n', mni_wm_file);
    fprintf('Using subject-specific MNI CSF map: %s\n', mni_csf_file);

    fprintf('Resampling subject-specific WM map to BOLD grid if needed.\n');
    wm_prob = resample_scalar_to_ref(mni_wm_file, ref_vol, 1);
    fprintf('Resampling subject-specific CSF map to BOLD grid if needed.\n');
    csf_prob = resample_scalar_to_ref(mni_csf_file, ref_vol, 1);

    wm_signal = extract_mask_mean_signal(data_4d, wm_prob, mask_3d, ...
        tpm_threshold, 'WM');
    csf_signal = extract_mask_mean_signal(data_4d, csf_prob, mask_3d, ...
        tpm_threshold, 'CSF');

    nuisance_raw = [motion_matrix, wm_signal(:), csf_signal(:)];
    labels = [motion_labels, {'wm_subject_mean', 'csf_subject_mean'}];

    [nuisance, nuisance_labels] = standardize_columns(nuisance_raw, labels);

    trend = linspace(-1.0, 1.0, n_timepoints)';
    design = [ones(n_timepoints, 1), trend, nuisance];
    design_labels = [{'intercept', 'linear_trend'}, nuisance_labels];

    design_rank = rank(design);
    if design_rank < size(design, 2)
        fprintf('Nuisance design is rank deficient: rank %d / %d.\n', ...
            design_rank, size(design, 2));
        fprintf('Pseudo-inverse regression will still be used.\n');
    end

    fprintf('Nuisance regressors used: %d columns.\n', numel(design_labels));
end


function ensure_subject_tissues_in_mni(deformation_file, native_wm_file, native_csf_file, ...
    mni_wm_file, mni_csf_file)

    input_files = {deformation_file, native_wm_file, native_csf_file};
    stale_wm = output_is_stale(mni_wm_file, input_files);
    stale_csf = output_is_stale(mni_csf_file, input_files);

    if ~stale_wm && ~stale_csf
        fprintf('Using existing subject-specific MNI WM map: %s\n', mni_wm_file);
        fprintf('Using existing subject-specific MNI CSF map: %s\n', mni_csf_file);
        return;
    end

    matlabbatch = [];
    matlabbatch{1}.spm.spatial.normalise.write.subj.def = {deformation_file};
    matlabbatch{1}.spm.spatial.normalise.write.subj.resample = { ...
        [native_wm_file ',1']; ...
        [native_csf_file ',1']};
    matlabbatch{1}.spm.spatial.normalise.write.woptions.bb = ...
        [-78 -112 -70; 78 76 85];
    matlabbatch{1}.spm.spatial.normalise.write.woptions.vox = [3 3 3];
    matlabbatch{1}.spm.spatial.normalise.write.woptions.interp = 1;
    matlabbatch{1}.spm.spatial.normalise.write.woptions.prefix = 'w';

    fprintf('Warping subject-specific WM/CSF maps to MNI with SPM.\n');
    spm_jobman('run', matlabbatch);

    ensure_file(mni_wm_file, 'subject-specific MNI WM probability map');
    ensure_file(mni_csf_file, 'subject-specific MNI CSF probability map');
end


function stale = output_is_stale(output_file, input_files)
    if exist(output_file, 'file') ~= 2
        stale = true;
        return;
    end

    output_info = dir(output_file);
    output_time = output_info.datenum;
    stale = false;

    for i = 1:numel(input_files)
        ensure_file(input_files{i}, 'input');
        input_info = dir(input_files{i});
        if input_info.datenum > output_time
            stale = true;
            return;
        end
    end
end


function [labels, matrix] = load_motion_regressors(motion_dir, n_timepoints)
    files = dir(fullfile(motion_dir, 'split_*', 'rp_*.txt'));
    if isempty(files)
        error('No rp_*.txt motion file found under: %s', motion_dir);
    end

    [~, order] = sort([files.datenum], 'descend');
    motion_file = fullfile(files(order(1)).folder, files(order(1)).name);
    motion = load(motion_file);

    if isvector(motion)
        motion = motion(:);
    end

    if size(motion, 1) ~= n_timepoints
        error(['Motion regressor rows do not match BOLD timepoints: ' ...
            '%s has %d rows, BOLD has %d.'], motion_file, size(motion, 1), ...
            n_timepoints);
    end

    if size(motion, 2) ~= 6
        error('Expected 6 motion columns in %s, got %d.', motion_file, size(motion, 2));
    end

    motion_diff = [zeros(1, 6); diff(motion, 1, 1)];
    motion_sq = motion .^ 2;
    motion_diff_sq = motion_diff .^ 2;

    names = {'x', 'y', 'z', 'pitch', 'roll', 'yaw'};
    labels = {};
    labels = [labels, add_prefix('motion_', names)];
    labels = [labels, add_prefix('motion_deriv_', names)];
    labels = [labels, add_prefix('motion_sq_', names)];
    labels = [labels, add_prefix('motion_deriv_sq_', names)];

    matrix = [motion, motion_diff, motion_sq, motion_diff_sq];
    fprintf('Using motion regressors: %s\n', motion_file);
    fprintf('Motion model: Friston 24 parameters.\n');
end


function labels = add_prefix(prefix, names)
    labels = cell(1, numel(names));
    for i = 1:numel(names)
        labels{i} = [prefix names{i}];
    end
end


function mean_signal = extract_mask_mean_signal(data_4d, tissue_prob, brain_mask, ...
    threshold, label)

    tissue_mask = tissue_prob >= threshold & brain_mask;
    voxel_count = nnz(tissue_mask);
    if voxel_count == 0
        error('%s TPM mask is empty after resampling and thresholding at %.3g.', ...
            label, threshold);
    end

    n_timepoints = size(data_4d, 4);
    flat_data = reshape(data_4d, [], n_timepoints);
    values = double(flat_data(tissue_mask(:), :));
    mean_signal = finite_nanmean_2d(values, 1);

    if any(~isfinite(mean_signal))
        error('%s mean signal contains non-finite values.', label);
    end

    fprintf('%s nuisance mask voxels: %d\n', label, voxel_count);
end


function mean_values = finite_nanmean_2d(values, dim)
    finite_values = isfinite(values);
    tmp = values;
    tmp(~finite_values) = 0;
    counts = sum(finite_values, dim);
    mean_values = sum(tmp, dim) ./ counts;
    mean_values(counts == 0) = NaN;
end


function [matrix_out, labels_out] = standardize_columns(matrix_in, labels_in)
    matrix_in = double(matrix_in);
    matrix_out = [];
    labels_out = {};

    for i = 1:size(matrix_in, 2)
        col = matrix_in(:, i);
        if any(~isfinite(col))
            error('Nuisance regressor contains non-finite values: %s', labels_in{i});
        end

        col = col - mean(col);
        col_std = std(col, 1);
        if col_std <= eps
            fprintf('Dropping constant nuisance regressor: %s\n', labels_in{i});
            continue;
        end

        matrix_out(:, end + 1) = col ./ col_std; %#ok<AGROW>
        labels_out{end + 1} = labels_in{i}; %#ok<AGROW>
    end
end


function [alff_data, valid_mask] = compute_alff(data_4d, mask_3d, nuisance_design, ...
    tr_seconds, low_freq, high_freq, chunk_size)

    n_timepoints = size(data_4d, 4);
    freqs = (0:floor(n_timepoints / 2)) ./ (n_timepoints * tr_seconds);
    low_band = freqs >= low_freq & freqs <= high_freq;

    if ~any(low_band)
        error(['No FFT bins found in low-frequency band %.6g-%.6g Hz. ' ...
            'Check TR=%.6g and timepoints=%d.'], low_freq, high_freq, ...
            tr_seconds, n_timepoints);
    end

    flat_data = reshape(data_4d, [], n_timepoints);
    masked_indices = find(mask_3d(:));

    alff_flat = zeros(numel(mask_3d), 1, 'single');
    valid_flat = false(numel(mask_3d), 1);

    design_pinv = pinv_with_rcond(nuisance_design, 1e-8);

    fprintf('TR: %.6g s\n', tr_seconds);
    fprintf('Timepoints: %d\n', n_timepoints);
    fprintf('Frequency resolution: %.6g Hz\n', freqs(2) - freqs(1));
    fprintf('Low-frequency band: %.6g-%.6g Hz\n', low_freq, high_freq);
    fprintf('Low-frequency FFT bins: %d\n', nnz(low_band));
    fprintf('Brain mask voxels: %d\n', numel(masked_indices));

    n_freqs = numel(freqs);

    for start_idx = 1:chunk_size:numel(masked_indices)
        stop_idx = min(start_idx + chunk_size - 1, numel(masked_indices));
        idx = masked_indices(start_idx:stop_idx);
        chunk = double(flat_data(idx, :));

        finite_rows = all(isfinite(chunk), 2);
        if ~any(finite_rows)
            continue;
        end

        valid_idx = idx(finite_rows);
        chunk = chunk(finite_rows, :);

        beta = chunk * design_pinv';
        fitted = beta * nuisance_design';
        chunk = chunk - fitted;

        fft_values = fft(chunk, [], 2);
        amplitude = abs(fft_values(:, 1:n_freqs)) .* (2.0 / n_timepoints);
        low_amp = amplitude(:, low_band);

        alff_flat(valid_idx) = single(mean(low_amp, 2));
        valid_flat(valid_idx) = true;

        fprintf('Processed voxels: %d/%d\n', stop_idx, numel(masked_indices));
    end

    alff_data = reshape(alff_flat, size(mask_3d));
    valid_mask = reshape(valid_flat, size(mask_3d));
end


function X_pinv = pinv_with_rcond(X, rcond_value)
    singular_values = svd(X, 'econ');
    if isempty(singular_values)
        X_pinv = pinv(X);
        return;
    end

    X_pinv = pinv(X, rcond_value * max(singular_values));
end


function save_3d_like(data_3d, ref_vol, out_file)
    Vout = ref_vol;
    Vout.fname = out_file;
    Vout.dim = ref_vol.dim;
    Vout.dt = [16 0];
    Vout.pinfo = [1; 0; 0];
    Vout.n = [1 1];
    Vout.descrip = 'mALFF nuisance-regressed';
    spm_write_vol(Vout, single(data_3d));
end
